#!/bin/sh
# ~/.shellrc - shell agnostic rc file, sourced by bashrc, zshrc etc.
# NOTE: Try to keep things in here sh-compliant.

#### Setup prompt colour ############################################
function getHostColour {
  #  31     32      33    34       35    36
  # red  green  yellow  blue  magenta  cyan
  case "$1" in
    Bear-Book.local ) echo "green" ;;
    Kat-Book.local ) echo "green" ;;
    Nookintosh.local  ) echo "green" ;;
    Sweetie ) echo "cyan"    ;;
    Luna    ) echo "cyan"   ;;
    Nook    ) echo "cyan"   ;;
    Kat-Tower ) echo "cyan"   ;;
    *        ) echo "yellow"     ;;
  esac
}

unamen="`uname -n`"
host_color="`getHostColour $unamen`"

function command_exists {
  hash "$1" &> /dev/null
}

# When connecting via ssh, always [re]attach to a terminal manager
if command_exists tmux && [ -z $TMUX ]; then
  if [ "$SSH_TTY" != "" -a "$TERM" -a "$TERM" != "screen" -a "$TERM" != "dumb" ]; then
    pgrep tmux
    # $? is the exit code of pgrep; 0 means there was a result (tmux is already running)
    if [ $? -eq 0 ]; then
      tmux -u attach -d
    else
      tmux -u
    fi
  fi
fi

#              _                            _
#  ___ _ ___ _(_)_ _ ___ _ _  _ __  ___ _ _| |_
# / -_) ' \ V / | '_/ _ \ ' \| '  \/ -_) ' \  _|
# \___|_||_\_/|_|_| \___/_||_|_|_|_\___|_||_\__|
# environment variables

export DOTDIR=$HOME/dots
export GOPATH=$HOME/go
export EDITOR="vim"
export PATH=$PATH
export PATH=$GOPATH/bin:$HOME/.local/bin:$HOME/local/bin:$HOME/.bin:$DOTDIR/bin:$PATH
export HISTCONTROL=ignoredups
export PAGER=less
export BROWSER=surf
export GREP_COLORS="mt=38;5;208:cx=38;5;246"

# see termcap(5)
export LESS_TERMCAP_md=$'\e[1;33m'
export LESS_TERMCAP_me=$'\e[m'
export LESS_TERMCAP_us=$'\e[0;32m'
export LESS_TERMCAP_ue=$'\e[m'
export LESS_TERMCAP_so=$'\e[0;40;38m'
export LESS_TERMCAP_se=$'\e[m'

export LSCOLORS=Gxfxcxdxbxegedabagacad

if [ "$TERM" = "xterm" ]; then
  TERM="${TERM}-256color"
fi

if [[ `uname` == Darwin ]]; then
  alias ls="ls -G"
else
  alias ls="ls --color"
fi

 #       _ _
 #  __ _| (_)__ _ ___ ___ ___
 # / _` | | / _` (_-</ -_|_-<
 # \__,_|_|_\__,_/__/\___/__/

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"
alias t="tmux attach"
alias grep="grep -i"
alias df="df -h"
alias du="du -hc"
alias ping="ping -c 5"
alias vi="vim"
alias sl="ls"
alias ll="ls -lah"
alias lsd="ls -la | grep '^d'"
alias feh="feh -FZ"
alias wallpaperme="feh --bg-fill"
alias iina="/Applications/IINA.app/Contents/MacOS/iina-cli"
alias atom="/Applications/Atom.app/Contents/Resources/app/atom.sh"
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"

#alias dockerCleanUp="docker rm $(docker ps -a -f STATUS=exited | awk '{print }')"
#alias dl="docker ps -a"
#alias ds="docker stop"
#alias dr="docker rm"
#alias dsa="docker stop $(docker ps -a -q)"
#alias dra="docker rm $(docker ps -a -q)"

# Enable aliases to be sudo’ed
alias sudo="sudo "

# Git shortcuts
alias g="git"
alias gs="git r1 -n 1; git branch | grep \*; git status --short"
alias gl="git log --decorate --oneline --graph --date-order --all"
alias ga="git add"
alias gp="git push"
alias gpa="gp --all"
alias gu="git pull"
alias gd="git diff"
alias gdc="gd --cached"
alias gm="git commit -m"
alias gma="git commit -am"
alias gb="git branch"
alias gba="git branch -a"
alias gcb="gc -b"
alias gf="git fetch"

## Filesystems
alias bf="du -x | sort -nr | head -10"
alias removeDot_="find . -iname '._*' -exec rm -rf {} \;"
alias cleandots="find . -regex '.*\(.AppleDouble\|.DS_Store\)$' -ls -exec rm -r {} \;"

# Convenience
alias scrot="scrot ~/screenshots/%Y-%m-%d_%H%M%S.png"
alias listmonofonts="fc-list :spacing=100 family style | sort -n"
alias updateFontCache="fc-cache -f -v"
alias xkeycap="xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'"
alias meminfo="echo -e '/proc/meminfo:\n';grep --color=auto '^[Mem|Swap]*[Free|Total]*:' /proc/meminfo && echo -e '\nfree -m:'; free -m"
alias listsoundcards="aplay -l | awk -F \: '/,/{print $2}' | awk '{print $1}' | uniq"
alias listsounddevices="aplay -L | grep :CARD"
alias ff_colours='for i in `seq 30 37`; do echo -e "\e[0;${i}m $i \e[1;${i}m $i \e[m"; done'
