#!/bin/sh
# ~/.shellrc - shell agnostic rc file, sourced by bashrc, zshrc etc.
# NOTE: Try to keep things in here sh-compliant.

# If there is a display attached, immediately start X
# This can have unexpected consequences.
#[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx


if [ "$TERM" = "xterm" ]; then
  TERM="${TERM}-256color"
fi


# Use the correct options on macOS and Linux
if [[ `uname` == Darwin ]]; then
  alias ls="ls -G"
else
  alias ls="ls --color"
fi


function command_exists {
  hash "$1" &> /dev/null
}


# When connecting via ssh, always [re]attach to a terminal manager
if command_exists tmux && [ -z $TMUX ]; then
  if [ "$SSH_TTY" != "" -a "$TERM" -a "$TERM" != "screen" -a "$TERM" != "dumb" ]; then
    pgrep tmux
    # $? is the exit code of pgrep; 0 means there was a result (tmux is already running)
    if [ $? -eq 0 ]; then
      tmux -u attach -d
    else
      tmux -u
    fi
  fi
fi


# To CD on Quit in NNN file manager
n ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # The behaviour is set to cd on quit with Ctl-G
	# prefix this line with "export" to ALWAYS cd on quit
    NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    stty start undef
    stty stop undef
    # stty lwrap undef
    # stty lnext undef

    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}


#              _                            _
#  ___ _ ___ _(_)_ _ ___ _ _  _ __  ___ _ _| |_
# / -_) ' \ V / | '_/ _ \ ' \| '  \/ -_) ' \  _|
# \___|_||_\_/|_|_| \___/_||_|_|_|_\___|_||_\__|
# environment variables

export DOTDIR=$HOME/dots
export GOPATH=$HOME/apps/go
export EDITOR="nvim"
export PATH=$GOPATH/bin:/opt/homebrew/bin:$HOME/.local/bin:$HOME/local/bin:$HOME/.bin:$DOTDIR/bin:$HOME/grimoire:$PATH

export HISTCONTROL=ignoredups
export PAGER=bat
export BROWSER=surf
export GREP_COLORS="mt=38;5;208:cx=38;5;246"
# for QT apps on 4k display
export QT_SCALE_FACTOR=1.2

# see termcap(5)
export LESS_TERMCAP_md=$'\e[1;33m'
export LESS_TERMCAP_me=$'\e[m'
export LESS_TERMCAP_us=$'\e[0;32m'
export LESS_TERMCAP_ue=$'\e[m'
export LESS_TERMCAP_so=$'\e[0;40;38m'
export LESS_TERMCAP_se=$'\e[m'

export LSCOLORS=Gxfxcxdxbxegedabagacad

# nnn file manager config
# g:-!git diff SHOW GIT DIFF FOR FILE
export NNN_PLUG='e:-!sudo -E nvim $nnn*;g:aFzcd;p:preview-tui;w:aWallpaper;d:dups;i:imgview'
export NNN_FIFO=/tmp/nnn.fifo
export NNN_OPENER=$HOME/.config/nnn/plugins/nuke
export SPLIT="v"

# fontpreview config
export FONTPREVIEW_PREVIEW_TEXT="Almost before we knew it,\nwe had left the ground.\n1234567890\n@#%&()~[]"
export FONTPREVIEW_FONT_SIZE="36"
export FONTPREVIEW_BG_COLOR="#241f33"
export FONTPREVIEW_FG_COLOR="#d1cae8"

#       _ _
#  __ _| (_)__ _ ___ ___ ___
# / _` | | / _` (_-</ -_|_-<
# \__,_|_|_\__,_/__/\___/__/
# shell aliases

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"
alias t="tmux attach"
alias r="ranger"
#alias n="nnn -e"
alias nnn="nnn -e"
alias N='sudo -E nnn -dH'
alias grep="grep -i"
alias df="df -h"
alias du="du -hc"
alias ping="ping -c 5"
alias vi="nvim"
alias ls="exa"
#alias sl="ls"
alias ll="exa -l"
alias lll="exa -abghHliS"
#alias ll="ls -lah"
#alias lsd="ls -la | grep '^d'"
alias feh="feh -FZ"
alias wallpaperme="feh --bg-fill"
alias iina="/Applications/IINA.app/Contents/MacOS/iina-cli"
alias atom="/Applications/Atom.app/Contents/Resources/app/atom.sh"
#alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"

# Enable aliases to be sudo’ed
alias sudo="sudo "
# Edit with sudo but use my prefs
alias svim="sudo -E nvim "

# Launch Krita with DPI scale factor
alias krita="env QT_SCALE_FACTOR=1.6 krita"
alias focus-wacom="xinput map-to-output 17 DisplayPort-0"
alias tubetoots="fd -a -e \"mp4\" . ~/visual/tubetoots | fzf | (nohup xargs -I{} mpv \"{}\" >/dev/null 2>&1 &)"
alias getWindowName="xprop | grep WM_CLAS"
alias getKeyName=""

alias decodot="python3 $DOTDIR/decodot.py"
alias decotheme="python3 $DOTDIR/decotheme.py"

# Git shortcuts
alias g="git"
alias gs="git r1 -n 1; git branch | grep \*; git status --short"
alias gl="git log --decorate --oneline --graph --date-order --all"
alias ga="git add"
alias gp="git push"
alias gpa="gp --all"
alias gu="git pull"
alias gd="git diff"
alias gdc="gd --cached"
alias gm="git commit -m"
alias gma="git commit -am"
alias gb="git branch"

# use Pokeget to draw a random pokemon sprite
# DIFF=$((898-1+1))
# R=$(($(($RANDOM%$DIFF))+X))
# pokeget -small $R

