#!/bin/bash

# Rewrites
alias t="tmux attach"
alias e="vim"
alias df="df -h"
alias du="du -hc"
alias ping="ping -c 5"
alias vi="vim"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"
alias ls="ls --color"
alias sl="ls"
alias ll="ls -lah"
alias lsd="ls -la | grep '^d'"
# fullscreen, auto-zoom images, montage mode
alias feh="feh -FZ"
alias stowdots="stow -t ~/ -d ~/Dropbox/dots"
alias musb="sudo mount /dev/sda1 /mnt/usb"
alias uusb="sudo umount /dev/sda1"
alias astow="stow -d $HOME/dots -t $HOME -S"
alias clean="find . -regex '.*\(.AppleDouble\|.DS_Store\)$' -ls -exec rm -r {} \;"

# Docker
# sweetie containers for serving files

alias docker-http="docker run --detach -it --rm -p 80:80 --name=\"http\" -v /mnt/mixed:/var/www clue/h5ai"

alias docker-afp="docker run -d -v /mnt/mixed:/media/mixed -v /mnt/tv:/media/tv -v /mnt/movies:/media/movies -v /mnt/extra_a:/media/empty_a -v /mnt/extra_b:/media/empty_b  -e AVAHI=1 --net \"host\" --name=\"afp\" -e AFP_USER=\"collector\" -e AFP_PASSWORD=pur3w0nd3r leafybear/afp"

alias docker-upnp="docker run -d --net=host -p 8200:8200 --name=\"upnp\" -v /mnt/upnp:/media -e MINIDLNA_MEDIA_DIR=V,/media -e MINIDLNA_ROOT_CONTAINER=V -e MINIDLNA_FRIENDLY_NAME=\"Hello Sweetie\" vladgh/minidlna"

# Capture XORG keys
alias xkeycap="xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'"

# Sound cards
alias soundcards="aplay -l | awk -F \: '/,/{print $2}' | awk '{print $1}' | uniq"
alias sounddevices="aplay -L | grep :CARD"

# Place scrot files in specified directory
#command -v scrot >/dev/null &&
alias scrot="scrot ~/screenshots/%Y-%m-%d_%H%M%S.png"

# Menu
alias menu="dmenu_run -i -nb $DMENU_NB -nf $DMENU_NF -sb $DMENU_SB -sf $DMENU_SF -fn \"$DMENU_FONT\""

# Git shortcuts
alias g="git"
alias gs="git r1 -n 1; git branch | grep \*; git status --short"
alias gl="git log --decorate --oneline --graph --date-order --all"
alias ga="git add"
alias gp="git push"
alias gpa="gp --all"
alias gu="git pull"
alias gd="git diff"
alias gdc="gd --cached"
alias gm="git commit -m"
alias gma="git commit -am"
alias gb="git branch"
alias gba="git branch -a"
alias gcb="gc -b"
alias gf="git fetch"

# Enable aliases to be sudo’ed
alias sudo="sudo "

# IP addresses
#alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"

# List 10 biggest files in pwd.
alias bf="du -x | sort -nr | head -10"

# List monospace fonts available
alias listmonofonts="fc-list :spacing=100 family style | sort -n"
alias updateFontCache="fc-cache -f -v"

# Memory status
alias meminfo="echo -e '/proc/meminfo:\n';grep --color=auto '^[Mem|Swap]*[Free|Total]*:' /proc/meminfo && echo -e '\nfree -m:'; free -m"
