" This must be first, because it changes other options as side effect
set nocompatible

"" - - - - - - - - - - - - - - - - - - - -
"" V U N D L E     P L U G I N S
filetype off                  " required for Vundle
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"" PLUGINS HERE
Plugin 'vim-airline/vim-airline'
Plugin 'airblade/vim-gitgutter'
Plugin 'preservim/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
" colors
Plugin 'lifepillar/vim-solarized8'
Plugin 'sainnhe/vim-color-forest-night'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
"" - - - - - - - - - - - - - - - - - - - - 

" don't make backups
set nobackup
set noswapfile

"" E D I T I N G
set hidden

set cursorline    " highlight current line in editor
set nowrap        " don't wrap lines
set tabstop=4     " a tab is four spaces
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set number        " always show line numbers
set shiftwidth=4  " number of spaces to use for autoindenting
set showmatch     " set show matching parenthesis
set ignorecase    " ignore case when searching
set smartcase     " ignore case if search pattern is all lowercase,
                    "    case-sensitive otherwise
set smarttab      " insert tabs on the start of a line according to
                    "    shiftwidth, not tabstop
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type
set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class
set title                " change the terminal's title
set visualbell           " don't beep
set noerrorbells         " don't beep
set encoding=utf-8		 " save files with UTF-8 encoding
" find bad whitespace in python files
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

"" K E Y M A P S
nnoremap j gj	" pressing down jumps to the next row 
nnoremap k gk	" 		in the editor (much more natural)

nnoremap gb :ls<CR>:b<Space>
map gn :bn<cr>	" 	next buffer
map gp :bp<cr>	"   previous buffer
map gd :bd<cr>  "	close buffer

"" P L U G I N   S E T T I N G S
map <C-n> :NERDTreeToggle<CR>
let g:airline#extensions#tabline#enabled = 1

" if you forgot to sudo before editing, hit :w!!
cmap w!! w !sudo tee % >/dev/null


"" - - - - - - - - - - - - - - - - - -
"" C O L O U R    S C H E M E S
if &t_Co >= 256 || has("gui_running")
	"" Solarized 8 Theme
"	set background=dark
"	colorscheme solarized8

	"" Forest Night Theme
	set termguicolors
"	let g:forest_night_enable_italic = 1
"	let g:forest_night_disable_italic_comment = 1
	let g:airline_theme = 'forest_night'
	colorscheme forest-night

endif

if &t_Co > 2 || has("gui_running")
    " switch syntax highlighting on, when the terminal has colors
    syntax on
endif
