#! /bin/sh

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm --load-state "$BSPWM_STATE"
	bspc wm --adopt-orphans
	rm "$BSPWM_STATE"
fi

sxhkd &

# colors in separate file
source $HOME/.theme/bspwm

# workspaces
# bspc monitor DisplayPort-0 -d cmd www art xtra
bspc monitor -d cmd www art xtra
bspc monitor HDMI-A-2 -d video reference chat

# visual options
bspc config border_width    2
bspc config window_gap      12
bspc config top_padding		0
bspc config right_padding	0
bspc config left_padding	0
bspc config bottom_padding	0

bspc config split_ratio         0.33
bspc config borderless_monocle  true
bspc config single_monocle 		true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer	true

bspc config super mod4

# desktop rules

# bspc desktop ^3 -l monocle
# bspc desktop ^4 -l monocle
# bspc desktop ^5 -l monocle

# app rules
bspc rule -a mpv state=floating sticky=on rectangle=400x250+40+40
bspc rule -a Gpick state=floating

bspc rule -a firefox desktop=^2 follow=on
bspc rule -a Blender desktop=^3 follow=on
bspc rule -a krita desktop=^3 follow=on
bspc rule -a Natron desktop=^3 follow=on
bspc rule -a surf desktop=^5
bspc rule -a Opera desktop=^5
bspc rule -a PureRef desktop=^6 
bspc rule -a XnView MP desktop=^6
bspc rule -a qimgv desktop=^6 #state=fullscreen
bspc rule -a discord desktop=^7
bspc rule -a Gpick state=floating

# set up a second screen if I have a script to do so.
if [ -x $DOTDIR/bin/secondDisplay.sh ]; then
	bash $DOTDIR/bin/secondDisplay.sh
fi

# start up apps
$HOME/.config/polybar/launch.sh &
kitty &
discord &
greenclip daemon &
