#! /bin/sh

#if [ -e "$BSPWM_STATE" ] ; then
#	bspc wm -l "$BSPWM_STATE"
#	rm "$BSPWM_STATE"
#fi

sxhkd &

# colors in separate file
source $HOME/.theme/bspwm

# workspaces
bspc monitor -d cmd edit www remote etc
bspc monitor HDMI2 -d cmd edit www remote etc
bspc desktop ^2 -l monocle
bspc desktop ^3 -l monocle

# visual options
bspc config border_width    1.5
bspc config window_gap      8
bspc config top_padding		34
bspc config right_padding	0
bspc config left_padding	0
bspc config bottom_padding	0

bspc config split_ratio         0.4
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer	true

bspc config super mod4

# app rules
bspc rule -a feh state=fullscreen
bspc rule -a mpv state=floating sticky=on rectangle=400x250+40+40
bspc rule -a Surf state=floating rectangle=500x900+40+40
bspc rule -a Sublime_text desktop=^2
bspc rule -a Vivaldi-stable desktop=^3
bspc rule -a Anki desktop=^5

# "use tabs consistently" external rules
#bspc config external_rules_command "$(which external_rules)"

# start up apps
$HOME/.config/polybar/launch.sh &
