#! /bin/sh

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm --load-state "$BSPWM_STATE"
	bspc wm --adopt-orphans
	rm "$BSPWM_STATE"
fi

sxhkd &

# colors in separate file
source $HOME/.theme/bspwm

# workspaces
bspc monitor -d cmd www 3d paint ? chat play 
# bspc monitor -d        
#         ﰟ           
# bspc monitor DisplayPort-0 -d 1 2 3
# bspc monitor HDMI-A-2 -d 1 2 3 

# do some different config for the laptop screen
case $HOSTNAME in
	"Lavender")
		bspc config window_gap      0
		bspc config split_ratio     0.5
		;;
	*)
		bspc config window_gap      10 
		bspc config split_ratio     0.33
		;;
esac

# visual options
bspc config border_width    0
bspc config single_monocle 	true

bspc config top_padding		0
bspc config right_padding	0
bspc config left_padding	0
bspc config bottom_padding	0

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer	true

bspc config super mod4

# desktop rules
bspc desktop ^3 -l monocle
# app rules
case $HOSTNAME in
# add definitions for floating windows for a laptop size screen
	"Lavender") bspc rule -a Blender desktop=^3 state=fullscreen follow=on;;
	*) 			bspc rule -a Blender desktop=^3 follow=on;;
esac

bspc rule -a djv state=floating sticky=on rectangle=1290x875+1827+251
bspc rule -a radeontop state=floating rectangle=838x544+1934+223
bspc rule -a mpv state=floating sticky=on rectangle=1290x875+1827+251
bspc rule -a "Pavucontrol" state=floating sticky=on rectangle=1290x875+1827+251
bspc rule -a "Lxappearance" state=floating sticky=on rectangle=1290x875+1827+251
bspc rule -a "Anki" state=floating sticky=on rectangle=875x875+1827+251

bspc rule -a Gpick state=floating

bspc rule -a surf desktop=^2
bspc rule -a Opera desktop=^2
bspc rule -a firefox desktop=^2 follow=on

bspc rule -a krita desktop=^4 follow=on
bspc rule -a Natron desktop=^4 follow=on
bspc rule -a grafx2 desktop=^4 follow=on
bspc rule -a "untitled - ArmorPaint" desktop=^4 follow=on
bspc rule -a resolve desktop=^4

bspc rule -a "PureRef" desktop=^5  follow=on
bspc rule -a XnView MP desktop=^5 follow=on
bspc rule -a qimgv desktop=^5 follow=on #state=fullscreen

bspc rule -a discord desktop=^6
bspc rule -a spotify desktop=^6

bspc rule -a Dwarf_Fortress desktop=^7 follow=on #state=fullscreen
bspc rule -a "Minecraft Launcher" desktop=^7 follow=on #state=fullscreen
bspc rule -a "Minecraft 1.18.1" desktop=^7 follow=on #state=fullscreen
bspc rule -a "Steam" desktop=^7 follow=on
bspc rule -a "retroarch" desktop=^7 follow=on

# set up a second screen if I have a script to do so.
# if [ -x $DOTDIR/bin/secondDisplay.sh ]; then
# 	bash $DOTDIR/bin/secondDisplay.sh
# fi

# start up apps
$HOME/.config/polybar/launch.sh &
$HOME/.config/dunst/launch.sh &
kitty &
# $HOME/local/Discord/Discord &
greenclip daemon &
blueman-applet &
