#### x settings and niceties
export XDG_CONFIG_HOME=$HOME/.config
export BSPWM_STATE=$HOME/.bspwm-state.json

xrdb $HOME/.Xresources
xsetroot -name $HOSTNAME
xsetroot -cursor_name left_ptr

sh ~/.fehbg &
#compton --config $HOME/.config/compton -cCb &
#xscreensaver -no-splash &

## set starting backlight and volume values
#xbacklight -set 50
amixer -q set Master 60 unmute
#/usr/bin/xcalib -d :0 $HOME/.icc/6000.icm

#### window manager
exec bspwm

# exec i3 -V >> ~/.i3-log-$(date + '%F-%k-%M-%S') 2>&1
