#### x settings and niceties
export XDG_CONFIG_HOME=$HOME/.config
export BSPWM_STATE=$HOME/.bspwm-state.json

xrdb $HOME/.Xresources
xsetroot -name $HOSTNAME
xsetroot -cursor_name left_ptr

sh ~/.fehbg &
#compton --config $HOME/.config/compton -cCb &
picom --experimental-backends &
dunst > /dev/null 2>&1 &
xscreensaver -no-splash &

#xbacklight -set 50
#/usr/bin/xcalib -d :0 $HOME/.icc/6000.icm
amixer -q set Master 60 unmute

#### window manager
# exec i3 -V >> ~/.i3-log-$(date + '%F-%k-%M-%S') 2>&1
#exec dwm
exec bspwm
